README.md

Signed-off-by: gprasath <giridhara.prasad@mayadata.io>
- describe the pipeline structure in readme

docs(readme): update pipeline content

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/1-cluster-setup/P7Q4-cluster-setup/cluster-setup
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/6-cleanup/cluster-cleanup

Included a script to create a konvoy cluster in AWS

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/1-cluster-setup/P7Q4-cluster-setup/cluster-setup
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/6-cleanup/cluster-cleanup

Signed-off-by: gprasath <giridhara.prasad@mayadata.io>
- updated gitlab-ci yaml
- update root privileges in cluster creation and deletion scripts

fix(yaml):update privileges in cluster creation and deletion scripts

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/1-cluster-setup/P7Q4-cluster-setup/cluster-setup

Signed-off-by: shashank855 <shashank.ranjan@mayadata.io>

Install docker as a part of Runner Script

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/1-cluster-setup/P7Q4-cluster-setup/cluster-setup

Signed-off-by: shashank855 <shashank.ranjan@mayadata.io>

Docker intallation fix

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/O21Y-openebs-deploy/infra-setup
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/utils/setup_dependencies

Signed-off-by: shashank855 <shashank.ranjan@mayadata.io>

Added openebs-konvoy-deploy stage

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/apps/cassandra/chaos/jiva/application-pod-failure
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/apps/mongo/chaos/jiva/volume-controller-failure
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/apps/percona/chaos/cstor/volume-target-failure

- Updated the data consistency check for the target failure script
- fix path issue in percona deployer script

refactor[script]: Updated chaos jobs to check the data consistency util

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/apps/percona/chaos/cstor/volume-target-failure
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/apps/percona/chaos/jiva/single-replica-failure

refactor[script]: Modified target failure and replica failure test scripts

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/O21Y-openebs-deploy/infra-setup
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/apps/percona/chaos/cstor/volume-target-failure

Modified and changed path openebs deploy script

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/apps/percona/chaos/cstor/volume-target-failure

refactor[test]: fix target failure test in OpenEBS base branch

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/1-cluster-setup/P7Q4-cluster-setup/cluster-setup

refactor[test]: Modified the cluster setup script in OpenebsBase branch

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/ACME-cstor-target-kill/README.md
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/DBVQ-cstor-pool-delete/README.md
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/DTCL-cstor-target-network-loss/README.md
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/FQFO-jiva-controller-kill/README.md
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/HVFC-snap-rebuild-single-rep/README.md
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/MVET-jiva-single-replica-failure/README.md
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/NSCD-Jiva-app-kill/README.md
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/OHQP-cstor-target-network-delay/README.md
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/QRSG-cstor-pool-mgmt-kill/README.md
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/README.md
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/REUZ-Jiva-replica-failure/README.md
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/TZZP-Jiva-controller-netwok-delay/README.md
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/UJOI-cstor-pool-kill/README.md
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/ZGNK-jiva-replica-node-affinity/README.md

Signed-off-by: gprasath <giridhara.prasad@mayadata.io>
- Added the chaos job details in their respective readme files.

doc(readme):add test details under chaos stage

---

.gitlab-ci.yml
openebs-konvoy-e2e/utils/e2e-cr
openebs-konvoy-e2e/utils/e2e-result.yml
openebs-konvoy-e2e/utils/litmus_job_runner

Signed-off-by: Aman Gupta aman.gupta@mayadata.io
1. Modify utils in konvoy-onprem

refactor[yaml]: Modify utils for konvoy-onprem

---

openebs-konvoy-e2e/utils/litmus_job_runner

1. Modified path in litmus job runner util.

refactor[yaml]: Update litmus_job_runner util in konvoy

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/ACME-cstor-target-kill/target-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/DBVQ-cstor-pool-delete/cstor-pool-delete
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/DTCL-target-network-loss/target-network-loss
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/FQFO-jiva-controller-kill/controller-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/HVFC-snap-rebuild-single-rep/snap-rebuild-single-rep
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/MCDE-app-kill/app-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/MVET-jiva-single-replica-failure/single-replica-failure
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/NSCD-Jiva-app-kill/jiva-app-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/REUZ-Jiva-replica-failure/jiva-replica-failure
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/TZZP-Jiva-controller-network-delay/controller-network-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/UJOI-cstor-pool-kill/cstor-pool-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/ZGNK-jiva-replica-node-affinity/replica-node-affinity

Signed-off-by: shashank855 <shashank.ranjan@mayadata.io>

Add chaos stage in konvoy-pipeline

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/SZRL-jiva-snapshot/jiva-snapshot
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/HVFC-snap-rebuild-single-rep/snap-rebuild-single-rep
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/LICZ-clone-post-snap-rebuild/clone-post-snap-rebuild

1. Added SZRL-jiva-snapshot in functional stage 
2. modified the path for cluster-cleanup stage

refactor[script]: Added jiva-snapshot job in functional stage

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/BRUC-create-cspc-stripe-pool/create-cspc-stripe-pool
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/HODS-deploy-csi-provisioner/deploy-csi-provisioner
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/OQEW-create-nfs-provisioner/nfsv4-provision
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/PIGE-storage-policies/openebs-sc
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/XJGT-openebs-deploy/infra-setup

1. Added cspc-striped-pool in Infra-setup stage.
2. Modified the storage pool and storage class name in csi-provisioner via sed command.

refactor[yaml]: Added cspc striped pool in konvoy Infra-setup

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/BRUC-create-cspc-stripe-pool/create-cspc-stripe-pool

1. Resolved the path issue in Infra-setup stage for cspc-stripe-pool

refactor[yaml]: Changed the path in cspc-stripe-pool for konvoy infra-setup stage

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/VQDN-deploy-percona-csi/deploy-percona-csi

1. Percona deployment job is added in konvoy-functional stage.
- Deployment is done using CSI.

feat[yaml]: Added Percona deployment using CSI in konvoy-functional.

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/VQDN-deploy-percona-csi/deploy-percona-csi

refactor[yaml]: Resolved the syntax error in Percona-CSI deployment

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/UAFE-rwx-app-deploy/rwx-app-deploy

1. modified storage class in UAFE-rwx-app-deploy in functional stage of konvoy pipeline

refactor[script]: modified storage class in rwx-app-deploy in functional stage of konvoy pipeline

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/THOJ-CVR-migration/cvr-migration

1. Added gitlab runner script for CVR-migration in functional experiments of release-branch
2. Updated .gitlab-ci.yml to include the CVR-migration test

feat[script]: Added gitlab runner script for CVR-migration

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/XJGT-openebs-deploy/infra-setup

1. changed the images to deploy-openebs in setup stage in konvoy-onprem

refactor[script]: changed the images to deploy-openebs in setup stage

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/CUVR-cstor-volume-istgt-kill/cstor-volume-istgt-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/ENEY-cstor-volume-mgmt-kill/cstor-volume-mgmt-kill

[skip ci]: Resolved typo in file name in volume istgt and mgmt kill 

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/FQFO-jiva-controller-failure/controller-failure
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/XUEK-jiva-controller-kill/jiva-controller-kill

1.Gitlab runner script for Jiva-controller-container-kill test is added in konvoy-onprem branch.

[skip ci]: Added gitlab script for jiva-controller-container-kill in konvoy onprem branch

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-upgrade-openebs/upgrade-control-plane
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-upgrade-openebs/upgrade-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-upgrade-openebs/upgrade-jiva

1. Added gitlab runner script for upgrade control plane
2. Added gitlab runner script for upgrade cstor
3. Added gitlab runner script for upgrade jiva

feat[script]: Added upgrade-openebs stage in upgrade-openebs branch

---

.gitlab-ci.yml

1. Id is modified in jiva-controller-kill.

[skip ci]: Resolved path/directory issue in gitlab-ci.yaml for konvoy-onprem

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/FQFO-jiva-controller-failure/controller-failure
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/XUEK-jiva-controller-kill/jiva-controller-kill

1. Gitlab runner script for **Jiva-controller-container-kill** test is added in release branch for konvoy.

[skip ci]: Added Gitlab runner script for jiva controller container kill in konvoy release branch

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/openebs-deploy/infra-setup
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/storage-policies/openebs-sc
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-upgrade-openebs/upgrade-control-plane
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-upgrade-openebs/upgrade-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-upgrade-openebs/upgrade-jiva

- Upgrade-openebs stage is added in upgrade branch.
- modified sed command to replace env's value correctly.

[skip ci]: Added upgrade openebs stage in Gitlab-ci.yaml in Upgrade branch

---

.gitlab-ci.yml

[skip ci]: resolved typo in gitlab-ci.yaml in upgrade branch

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/openebs-deploy/infra-setup
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-upgrade-openebs/upgrade-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-upgrade-openebs/upgrade-jiva

- fixed the gitlab ci yaml and upgrade openebs scripts

refactor[script]: Modified the gitlab scripts for the upgrade openebs pipeline

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-cstor-clone/busybox-cstor-clone
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-cstor-snapshot/busybox-cstor-snapshot
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-deployment-cstor/busybox-deployment-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-deployment-jiva/busybox-deployment-jiva
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-jiva-snapshot/busybox-jiva-snapshot
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-statefulset-cstor/busybox-statefulset-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-statefulset-jiva/busybox-statefulset-jiva
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/percona-deployment-cstor/percona-deployment-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/percona-deployment-jiva/percona-deployment-jiva
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-controller-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-cstor-pool-delete
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-cstor-pool-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-cstor-verify-data-persistence
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-deployment-controller-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-deployment-target-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-jiva-verify-data-persistence
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-target-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-cotroller-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-target-nw-delay

- resolved typo in $user@$ip in ssh command.

[skip ci]: Resolved typo in ssh to konvoy cluster in upgrade branch

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/openebs-deploy/infra-setup

refactor[script]: Updated the release tag for infra setup script

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/6-cleanup/cluster-cleanup/cluster-cleanup

- modified path for checkout to upgrade-openebs branch.

[skip ci]: Modified path for checkout to upgrade-openebs branch in cleanup stage

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/XUEK-jiva-controller-kill/jiva-controller-kill

- Modified the litmus job runner label.

[skip ci]: Modified the label name in jiva-controller-kill test in release branch

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/XUEK-jiva-controller-kill/jiva-controller-kill

- litmus job runner label is modified.

[slip ci]: Modified label name in jiva-controller-kill in onprem branch

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-cstor-clone/busybox-cstor-clone
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-cstor-snapshot/busybox-cstor-snapshot
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-deployment-cstor/busybox-deployment-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-deployment-jiva/busybox-deployment-jiva
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-jiva-snapshot/busybox-jiva-snapshot
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-statefulset-cstor/busybox-statefulset-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-statefulset-jiva/busybox-statefulset-jiva
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/percona-deployment-cstor/percona-deployment-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/percona-deployment-jiva/percona-deployment-jiva
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-controller-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-cstor-pool-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-cstor-verify-data-persistence
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-deployment-controller-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-deployment-target-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-jiva-verify-data-persistence
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-cotroller-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-target-nw-delay

- modified path names for litmus experiments
- modified labels name specific to the litmus exeriments.

[skip ci]: Modified litmus job runners label names for chaos jobs in upgrade branch

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-cstor-clone/busybox-cstor-clone
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-cstor-snapshot/busybox-cstor-snapshot
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-deployment-cstor/busybox-deployment-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-deployment-jiva/busybox-deployment-jiva
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-jiva-snapshot/busybox-jiva-snapshot
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-statefulset-cstor/busybox-statefulset-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-statefulset-jiva/busybox-statefulset-jiva
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/percona-deployment-cstor/percona-deployment-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/percona-deployment-jiva/percona-deployment-jiva
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-upgrade-openebs/upgrade-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-upgrade-openebs/upgrade-jiva
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-controller-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-cstor-pool-delete
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-cstor-pool-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-cstor-verify-data-persistence
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-deployment-controller-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-deployment-target-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-jiva-verify-data-persistence
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-target-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-cotroller-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-target-nw-delay

- resolved typos.
- append run id in test case name
- modified sed commands

[skip ci]: Append run id in testcase name in upgrade branch

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/SHOZ-target-network-delay/target-network-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/UJOI-cstor-pool-kill/cstor-pool-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/XUEK-jiva-controller-kill/jiva-controller-kill

1. Enabled data persistency in cstor-pool-kill
2. Modified the container runtime to containerd

refactor[script]: Enabled data persistency in cstor-pool-kill

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/SHOZ-target-network-delay/target-network-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/UJOI-cstor-pool-kill/cstor-pool-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/XUEK-jiva-controller-kill/jiva-controller-kill

1. Enabled the data persistency in cstor pool kill in release-branch
2. modified the container runtime to containerd

refactor[script]: Enabled the data persistency in cstor pool kill in release-branch

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/DTCL-target-network-loss/target-network-loss
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/SHOZ-target-network-delay/target-network-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/TZZP-Jiva-controller-network-delay/controller-network-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/XUEK-jiva-controller-kill/jiva-controller-kill

1. Enabled the data persistency in target network loss
2. Enabled the data persistency in controller network delay

refactor[script]: Enabled the data persistency in target network loss in release-branch

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/LCDG-Backup-Restore/backup-restore
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/XUEK-jiva-controller-kill/jiva-controller-kill

1. Added gitlab runner for velero backup and restore

feat[script]: Added gitlab runner script for velero backup and restore

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/DTCL-target-network-loss/target-network-loss
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/SHOZ-target-network-delay/target-network-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/TZZP-Jiva-controller-network-delay/controller-network-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/XUEK-jiva-controller-kill/jiva-controller-kill

1. Enabled the data persistency in target network loss 
2. Enabled the data persistency in controller network delay

refactor[script]: Enabled the data persistency in target network loss in konvoy-onprem

---

.gitlab-ci.yml

1. Removed the job jiva controller kill from konvoy-onprem branch

refactor[script]: Removed the job jiva controller kill from konvoy-onprem branch

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/XUEK-jiva-controller-kill/jiva-controller-kill

1. Updated the container runtime to containerd in jiva controller kill

refactor[script]: Updated the container runtime to containerd in jiva controller kill

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/MQVF-csi-cstor-clone/csi-cstor-clone
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/MSIT-csi-cstor-snapshot/csi-cstor-snapshot
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/6-cleanup/ISTV-cluster-cleanup/cluster-cleanup

1. Added gitlab runner script for csi snapshot and clone

feat[script]: Added gitlab runner script for csi snapshot and clone

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/HZWT-cvr-scaledown/cvr-scaledown
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/RUTT-cvr-scaleup/cvr-scaleup

- Gitlab runner script is added in konvoy-onprem branch for
1. CVR-scale up
2. CVR-scale down

feat[script]: Added CVR-scaleup and scale down gitlab runner script in konvoy release branch

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/MQVF-csi-cstor-clone/csi-cstor-clone
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/MSIT-csi-cstor-snapshot/csi-cstor-snapshot

1. Modified storage class according to csi-provisioner in csi snapshot and clone jobs

refactor[script]: Modified csi snapshot and clone jobs

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/HZWT-cvr-scaledown/cvr-scaledown
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/MSIT-csi-cstor-snapshot/csi-cstor-snapshot
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/RUTT-cvr-scaleup/cvr-scaleup
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/DTCL-target-network-loss/target-network-loss

1. fixed sed commands in gitlab runnner script for the csi-snapshot

refactor[script]: fixed sed commands in gitlab runnner script for the csi-snapshot

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/HZWT-cvr-scaledown/cvr-scaledown
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/LCDG-Backup-Restore/backup-restore
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/RUTT-cvr-scaleup/cvr-scaleup
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/DTCL-target-network-loss/target-network-loss
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/6-cleanup/ISTV-cluster-cleanup/cluster-cleanup

[skip ci]: Modified the branch name in checkout command in cluster cleanup stage in release branch

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/HZWT-cvr-scaledown/cvr-scaledown
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/6-cleanup/ISTV-cluster-cleanup/cluster-cleanup

[skip ci]: Modified the cvr scale down script to resolve typo

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/openebs-deploy/infra-setup
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-cstor-clone/busybox-cstor-clone
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-cstor-snapshot/busybox-cstor-snapshot
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-deployment-cstor/busybox-deployment-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-deployment-jiva/busybox-deployment-jiva
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-jiva-snapshot/busybox-jiva-snapshot
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-statefulset-cstor/busybox-statefulset-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-statefulset-jiva/busybox-statefulset-jiva
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/percona-deployment-cstor/percona-deployment-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/percona-deployment-jiva/percona-deployment-jiva
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-controller-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-cstor-pool-delete
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-cstor-pool-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-cstor-verify-data-persistence
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-deployment-controller-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-deployment-target-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-jiva-verify-data-persistence
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-target-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-controller-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-target-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/6-cleanup/cluster-cleanup/cluster-cleanup

- resolved typos.
- modified sed commands.
- resolved the path/directory not found issue.

[skip ci]: Modified the sed commands and litmus_job_runner labels in upgrade branch

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/1-cluster-setup/cluster-setup/cluster-setup
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/openebs-deploy/infra-setup

refactor(script): Modify the gitlab script to resolve typo in deploy-openebs script

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-cstor-clone/busybox-cstor-clone
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-cstor-snapshot/busybox-cstor-snapshot
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-deployment-cstor/busybox-deployment-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-deployment-jiva/busybox-deployment-jiva
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-jiva-snapshot/busybox-jiva-snapshot
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-statefulset-cstor/busybox-statefulset-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-statefulset-jiva/busybox-statefulset-jiva
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/percona-deployment-cstor/percona-deployment-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/percona-deployment-jiva/percona-deployment-jiva
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-upgrade-openebs/upgrade-control-plane
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-controller-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-cstor-pool-delete
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-cstor-pool-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-cstor-verify-data-persistence
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-deployment-controller-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-deployment-target-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-jiva-verify-data-persistence
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-target-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-controller-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-target-nw-delay

refactor(yaml): Modified the upgrade-openebs branch to resolve typos and configmap names

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-controller-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-cstor-pool-delete
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-cstor-pool-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-cstor-verify-data-persistence
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-deployment-controller-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-deployment-target-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-jiva-verify-data-persistence
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-target-kill

refactor(yaml): Added pooling task in jobs gitlab script in upgrade branch

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-statefulset-cstor/busybox-statefulset-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/busybox-statefulset-jiva/busybox-statefulset-jiva
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-upgrade-openebs/upgrade-control-plane
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-controller-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-cstor-verify-data-persistence
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-deployment-controller-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-deployment-target-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-jiva-verify-data-persistence
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-target-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-controller-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-target-nw-delay

refactor(script): Modified the gitlab script in upgrade branch to resolve data persistence parameters

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-upgrade-openebs/upgrade-control-plane
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-deployment-controller-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-deployment-target-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-controller-nw-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-target-nw-delay

refactor(script): Modified the bash parameters in control plane upgrade gitlab script

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-deployment-controller-nw-delay

- resolved typo in sed command

refactor(script): Modified the controller network delay script in upgrade branch

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/MQVF-csi-cstor-clone/csi-cstor-clone
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/MSIT-csi-cstor-snapshot/csi-cstor-snapshot

1. Modified sed commands in csi snapshot and clone
2. Included csi snapshot and delete runner script

refactor[script]: Modified sed commands in csi snapshot and clone

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/MQVF-csi-cstor-clone/csi-cstor-clone

1. modified sed command in gitlab runner script to deprovision csi-clone

refactor[script]: modified gitlab runner script to deprovision csi-clone

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/MQVF-csi-cstor-clone/csi-cstor-clone

1. Modified sed command in csi-clone-deletion

refactor[script]: Modified sed command in csi-clone-deletion

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/NLEQ-local-pv-hostpath/local-pv-hostpath
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/ZDKG-local-pv-device/local-pv-device

feat(script): Included a gitlab script to perform the Application provision using Local PV

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/NLEQ-local-pv-hostpath/local-pv-hostpath
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/ZDKG-local-pv-device/local-pv-device

[skip ci]: Fixed the generate test name script to provision local pv

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-cstor-clone
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-deployment-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-deployment-jiva

- Deployed percona application with jiva and cstor after upgrading openebs components
- Create clone from the snapshot taken in functional stage
- Modified gitlab-ci.yaml

feat(script): Added percona application deployment after upgrade openebs in upgrade branch

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/NLEQ-local-pv-hostpath/local-pv-hostpath
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/ZDKG-local-pv-device/local-pv-device

refactor(script): Modified the test scripts for local pv provision

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/DTCL-target-network-loss/target-network-loss

- Added kubectl command to delete all pods in job namespace

refactor(yaml): Modified the target nw loss experiment gitlab script in konvoy release branch

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-upgrade-openebs/upgrade-control-plane
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-upgrade-openebs/upgrade-cstor

refactor[script]: Included a condition to get the image tag for upgrade scripts

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/RACV-node-failure-cstor/node-failure-cstor

1. Added gitlab runner script for cstor-node-failure.

feat[script]: Added gitlab runner script for cstor-node-failure

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/DTCL-target-network-loss/target-network-loss

1. Modified target network loss to validate csi volume remount

refactor[script]: Modified target network loss to validate csi volume remount

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/ABZF-csi-volume-resize/csi-volume-resize
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/DTCL-target-network-loss/target-network-loss

1. Disabled the target pod affinity in target network loss gitlab runner script.
2. Updated the jobname of csi-volume-resize to csi-volume-resize-ext4.
3. Updated the storage class in csi-volume-resize-ext4

refactor[script]: Modified target pod affinity in target network loss

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/ARZQ-csi-volume-resize-xfs/csi-volume-resize-xfs
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/DTCL-target-network-loss/target-network-loss

1. Added gitlab runner script for csi-volume-resize-xfs in functional stage

feat[script]: Added gitlab runner script for csi-volume-resize-xfs in functional stage

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/DTCL-target-network-loss/target-network-loss
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/ECBZ-kubelet-failure-cstor/kubelet-failure-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/RACV-node-failure-cstor/node-failure-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/UUPF-containerd-failure-cstor/containerd-failure-cstor

- Added containerd failure chaos gitlab script
- Added kubelet failure chaos gitlab script

feat(script): Added containerd failure and kubelet failure service chaos gitlab script in konvoy release branch

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/ECBZ-kubelet-failure-cstor/kubelet-failure-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/UUPF-containerd-failure-cstor/containerd-failure-cstor

- Modify the sed command
- resolve typo

refactor(script): Modify the sed command in service failure chaos gitlab script

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/ECBZ-kubelet-failure-cstor/kubelet-failure-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/UUPF-containerd-failure-cstor/containerd-failure-cstor

1. Modified sed commands in infra stage of release-branch

refactor[script]: Modified sed commands in infra stage of release-branch

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/ABZF-csi-volume-resize/csi-volume-resize
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/ARZQ-csi-volume-resize-xfs/csi-volume-resize-xfs
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-chaos/DTCL-target-network-loss/target-network-loss
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/ECBZ-kubelet-failure-cstor/kubelet-failure-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/RACV-node-failure-cstor/node-failure-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/UUPF-containerd-failure-cstor/containerd-failure-cstor

1. Added gitlab runner script for test csi volume resize with fstype xfs.
2. Added gitlab runner script for test kubelet failure cstor.
3. Added gitlab runner script for test node failure cstor.
4. Added gitlab runner script for test containerd failure cstor.
5. Modified job name of csi-volume-resize to csi-volume-resize-ext4.
6. Modified target network loss to implement cstor csi volume remount.

feat[script]: Included infra-chaos stage in konvoy-onprem

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/percona-localpv-device/percona-localpv-device
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/percona-localpv-hostpath/percona-localpv-hostpath
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-deployment-device
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-deployment-hostpath
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-verify-data-persistence-device
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-verify-data-persistence-hostpath

- Included a localpv related testcases in upgrade pipeline

feat(test): Included a localpv related testcases in upgrade pipeline

---

.gitlab-ci.yml

feat(test): Included application deploy using localpv into ci yaml

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-verify-data-persistence-device
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-verify-data-persistence-hostpath

Included a test to verify the data persistence for application using localpv

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/CFKB-cstor-thick-provisioning/cstor-thick-provisioning

- GItlab script added for implementing cstor thick provisioning
- first striped pool is created and used this pool in thick provisioning

add(script): Added gitlab script for implementing cstor thick provisioning in konvoy release branch 

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/BRUC-create-cspc-stripe-pool/create-cspc-stripe-pool
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/XJGT-openebs-deploy/infra-setup
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/XMOM-create-cspc-mirror-pool/create-cspc-mirror-pool
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/ESML-cstor-cspc-pool-expansion/cstor-cspc-pool-expansion
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/JIGL-cstor-cspc-pool-scaleup/cstor-cspc-pool-scaleup
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/JULL-cstor-cspc-pool-replace-blockdevice/cstor-cspc-pool-replace-blockdevice

feat[test]: Included a test cases for pool scaleup,expansion and device replacement into pipeline

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/JIGL-cstor-cspc-pool-scaleup/cstor-cspc-pool-scaleup

refactor[script]: Fixed the typo in job name of pool scaleup test

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/XJGT-openebs-deploy/infra-setup

- PR against issue:https://github.com/mayadata-io/litmus/issues/170

Refactor script to echo openebs release tag in gitlab log

---

openebs-konvoy-e2e/utils/litmus_job_runner

- Resolve syntax error in litmus job runner util in konvoy release branch

refactor(yaml): Resolve syntax error in litmus job runner util in konvoy release branch

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/LCDG-Backup-Restore/backup-restore

- Refactor backup & restore to use GCP bucket & velero version from Gitlab env

Refactor backup & restore to use GCP bucket & velero version from Gitlab env

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/LCDG-Backup-Restore/backup-restore

fix(bakup and restore script): To get sdk_token from gitlab-env

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/JULL-cstor-cspc-pool-replace-blockdevice/cstor-cspc-pool-replace-blockdevice

- Resolved the path issue in blockdeviece replace job for cspc pool

refactor(script): Resolved the path issue in cstor-cspc-pool-bd-replace job in konvoy release branch

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/C55O-pdb-cspc/pdb-cspc
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/RACV-node-failure-cstor/node-failure-cstor

Include test for cspc pdb in konvoy pipeline

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/C55O-pdb-cspc/pdb-cspc

- Refactor CSPC-PDB script to put node affinity in litmus job spec

Refactor CSPC-PDB script to put node affinity in litmus job spec

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/JULL-cstor-cspc-pool-replace-blockdevice/cstor-cspc-pool-replace-blockdevice

Refactor disk-replace sript to pass correct job label

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/C55O-pdb-cspc/pdb-cspc

[skip ci]: Modified cspc-pdb test gitlab script in konvoy pipeline to resolve script failures

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/ABZF-csi-volume-resize/csi-volume-resize
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/ARZQ-csi-volume-resize-xfs/csi-volume-resize-xfs

-  Modified the path directory for csi-vol-resize playbook.
- Modified the sed command to take test specific env's

refactor(script): Modified csi-vol resize scripts for the latest changes in the playbook path directory

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/LTWY-jiva-volume-resize/jiva-volume-resize

1. Included the job Jiva Volume Resize into the pipeline.
2. Modified the .gitlab-ci.yml

feat[script]: Included the job Jiva Volume Resize into the pipeline

---

.gitlab-ci.yml

1. Commented out the job jiva internal snapshot deletion
2. modified the .giutlab-ci.yml

refactor[script]: Commented out the job jiva internal snapshot deletion

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/HODS-deploy-csi-provisioner/deploy-csi-provisioner

refactor[script]: Modified the script for csi provisioner

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/LUUY-kubelet-failure-jiva/kubelet-failure-jiva
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/RACV-node-failure-cstor/node-failure-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/SXRU-node-failure-jiva/node-failure-jiva
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/VVCU-containerd-failure-jiva/containerd-failure-jiva

1. Added node failure for jiva volume
2. Added containerd failure for jiva volume
3. Added kubelet failure for jiva volume
4. Included the jobs in .gitlab-ci

feat[script]: Included infra-chaos jobs for jiva volume

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/HODS-deploy-csi-provisioner/deploy-csi-provisioner

Updated the sed command in deploy csi provisioner script

---

.gitlab-ci.yml

refactor[gitlab-yaml]: Modified the dependecies of stages in gitlab ci  yaml

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/6-csi-infra-setup/AWES-cstor-operator/cstor-operator
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/9-csi-infra-chaos/C55O-pdb-cspc/pdb-cspc

[skip ci]: Fixed path issue in cstor-operator runner script

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/8-csi-chaos/AYQM-cstor-app-kill/app-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/8-csi-chaos/NTAV-cstor-target-kill/target-kill

Modified the test scripts for cstor csi chaos

---

.gitlab-ci.yml

Fixed path issue in gitlab ci yaml

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/8-csi-chaos/AYQM-cstor-app-kill/app-kill
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/8-csi-chaos/NTAV-cstor-target-kill/target-kill

Refactor the gitlab scripts for csi chaos stage

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/RACV-node-failure-cstor/node-failure-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/SXRU-node-failure-jiva/node-failure-jiva

1. Modified the sed command in node_failure jobs.

refactor[script]: Modified the sed command in node_failure

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/RACV-node-failure-cstor/node-failure-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/VVCU-containerd-failure-jiva/containerd-failure-jiva

Refactor the gitlab script for infra chaos jobs

---

.gitlab-ci.yml

Modified the gitlaci yaml changed the jobs for cspc

---

.gitlab-ci.yml

refactor[ci-yaml]: Included a tests for csi functional and chaos stages

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/10-cleanup/ISTV-cluster-cleanup/cluster-cleanup

Signed-off-by: gprasath <giridhara.prasad@mayadata.io>
- updated repo details
- updated IP address of ESX machine

refactor(script): update IP address and repo details

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/ECBZ-kubelet-failure-cstor/kubelet-failure-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/LUUY-kubelet-failure-jiva/kubelet-failure-jiva
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/RACV-node-failure-cstor/node-failure-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/SXRU-node-failure-jiva/node-failure-jiva
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/UUPF-containerd-failure-cstor/containerd-failure-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/VVCU-containerd-failure-jiva/containerd-failure-jiva
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/8-csi-chaos/NTAV-cstor-target-kill/target-kill

refactor[infra-script]: Changed the esx ip in the test scripts

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/XJGT-openebs-deploy/infra-setup

- Now images env will be taken from gitlab env's

Modified the openebs deployment test script to get the image as env in konvoy pipeline

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/XJGT-openebs-deploy/infra-setup

Resolved the directory issue in openebs-provision script

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/7-csi-functional/LCWN-csi-volume-scaledown/csi-volume-scaledown
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/7-csi-functional/STBD-csi-volume-scalup/csi-volume-scaleup

Fixes: https://github.com/mayadata-io/e2e-konvoy/issues/155
- This PR adds pipeline script for following tests
1. cstor-csi-volume scaleup
2. cstor-csi-volume scaledown

add(script): Add cstor-csi volume-scale tests into konvoy pipeline

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/7-csi-functional/LCWN-csi-volume-scaledown/csi-volume-scaledown
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/7-csi-functional/STBD-csi-volume-scaleup/csi-volume-scaleup

- Resolved the typo in file name for csi-volume-scaleup
- Added configmap spec in scaling test to use data-persistence

refact(script): Added configmap spec to check data-persistence

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/7-csi-functional/LCWN-csi-volume-scaledown/csi-volume-scaledown
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/7-csi-functional/STBD-csi-volume-scaleup/csi-volume-scaleup

- Modified the litmus job label in csi volume scaleup and csi volume scaledown test scripts to get the status of litmus job

fix[script]: Modified the test script for csi volume scaleup and scaledown tests

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/7-csi-functional/HNOV-Backup-Restore-Cstor/backup-restore-cstor-csi
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/7-csi-functional/OTQI-Backup-Restore-Diff-Profile/backup-restore-diff-profile
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/7-csi-functional/XYNP-Remote-Restore-Diff-ns/remote-restore-diff-ns

Signed-off-by: <ranjanshashank855@gmail.com>
Adds following experiments CSI based backup/restore experiments into the piepeline:
- Backup/restore 
- Remote restore in different namespace.
- Backup/Restore using different S3 profile.
- https://github.com/openebs/e2e-tests/issues/406

[skip-ci]: feat(add): Backup/restore experiments for CSI volumes

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/7-csi-functional/HNOV-Backup-Restore-Cstor/backup-restore-cstor-csi
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/7-csi-functional/OTQI-Backup-Restore-Diff-Profile/backup-restore-diff-profile
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/7-csi-functional/XYNP-Remote-Restore-Diff-ns/remote-restore-diff-ns

Signed-off-by: <ranjanshashank855@gmail.com>

Refactor(Backup/restore CSI-Jobs): To disable target affinity in app deployment

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/LCDG-Backup-Restore/backup-restore

Signed-off-by: <ranjanshashank855@gmail.com>

refactor(backup-restore): To deprovision velero after test completion

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/8-csi-chaos/VBCV-cstor-target-network-delay/target-network-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/8-csi-chaos/ZCCC-cspc-cstor-pool-kill/cspc-cstor-pool-kill

- In this PR included a test script for cStor pool container kill in cspc pool and target network delay on csi based volumes

feat[test]: Included a test to perform chaos on cspc csi based volumes

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/8-csi-chaos/VBCV-cstor-target-network-delay/target-network-delay
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/8-csi-chaos/ZCCC-cspc-cstor-pool-kill/cspc-cstor-pool-kill

- fixed the typo in cspc pool kill and csi target network delay test

fix[typo]: Modified the test script for csi chaos

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/6-csi-infra-setup/HODS-deploy-csi-provisioner/deploy-csi-provisioner

refactor[script]: Modified the script for provision csi plugins

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/10-cleanup/ISTV-cluster-cleanup/cluster-cleanup

- A new cluster with konvoy4.5 has been created changed the ip in cluster cleanup script for the newly created cluster

refactor[script]: Modified the vm name and ip in cluster revert test script

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/LLJA-Jiva-internal-snapshot-deletion/Jiva-internal-snapshot-deletion

Signed-off-by: <ranjanshashank855@gmail.com>
- Excludes experiment for jiva pods in OpenEBS namespace.
- Includes Jiva autogen snapshot delete(with RANDOM restart of replica) experiment in to pipeline.

refactor(script): Include Jiva autogen snapshot delete in konvoy pipeline

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/6-csi-infra-setup/AWES-cstor-operator/cstor-operator

- Changed the test case file name for cstor operator provision

fix[path]: Changed the test case file path for cstor-operator

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/PIGE-storage-policies/openebs-sc
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/6-csi-infra-setup/AWES-cstor-operator/cstor-operator
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/6-csi-infra-setup/GUGS-csi-storage-policies/openebs-csi-sc
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/7-csi-functional/BNEX-blockdevice-reusability/blockdevice-reusability
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/7-csi-functional/NVOZ-block-pool-creation-with-claimed-bd/block-pool-creation-with-claimed-bd
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/7-csi-functional/TUTQ-block-pool-deletion-with-volume/block-pool-deletion-with-volume
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/9-csi-infra-chaos/KAPB-node-failure-csi-cstor/node-failure-csi-cstor

- Modified the paths and job names and fixed typos in test script

refactor[scripts]: Modified the file path and test names in csi related test cases

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/7-csi-functional/BNEX-blockdevice-reusability/blockdevice-reusability
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/7-csi-functional/OTQI-Backup-Restore-Diff-Profile/backup-restore-diff-profile

fix[script]: Resolved the lint issues in test scripts

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-infra-chaos/RACV-node-failure-cstor/node-failure-cstor

- This PR fixes the sed command to update the secret values for node and esx password.

[skip ci]: fixed the sed command to update the secret values

---

.gitlab-ci.yml
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/9-csi-infra-chaos/KAPB-node-failure-csi-cstor/node-failure-csi-cstor
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/9-csi-infra-chaos/WXVN-containerd-failure-csi-cstor/containerd-failure-csi-cstor

- Included a test script for container run time test failure in csi based cstor volume

feat(skip_ci): Included a test script for container runtime failure for csi based cstor volume

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/9-csi-infra-chaos/KAPB-node-failure-csi-cstor/node-failure-csi-cstor

- fixed the secret name for node-password

[skip ci]: fixed the secret name for node-password

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/9-csi-infra-chaos/WXVN-containerd-failure-csi-cstor/containerd-failure-csi-cstor

- Changed the configmap name and secret name in containerd failure test scripts

refactor(script): Modified the configmap name in containerd failure test

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/9-csi-infra-chaos/WXVN-containerd-failure-csi-cstor/containerd-failure-csi-cstor

fix(label): Modified the label name for container failure test case

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/8-csi-chaos/AYQM-cstor-app-kill/app-kill

- Append the run id for cstor csi app kill test

fix(run_id): changed the typo in run id for csi cstor app kill test

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/LCDG-Backup-Restore/backup-restore

refactor[script]: Modified the application deployment scripts in backup restore test

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/2-Infra-setup/XJGT-openebs-deploy/infra-setup
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/LCDG-Backup-Restore/backup-restore
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/7-csi-functional/HNOV-Backup-Restore-Cstor/backup-restore-cstor-csi
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/7-csi-functional/OTQI-Backup-Restore-Diff-Profile/backup-restore-diff-profile
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/7-csi-functional/XYNP-Remote-Restore-Diff-ns/remote-restore-diff-ns

refactor[script]: Updated the test scripts for backup and restore

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/6-csi-infra-setup/AWES-cstor-operator/cstor-operator
openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/7-csi-functional/7D85-fail-pool-expansion-with-claimed-bd/fail-pool-expansion-with-claimed-bd

Included a test to verify the pool expansion is blocked when bd is in claimed state

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/6-csi-infra-setup/AWES-cstor-operator/cstor-operator

skip_ci: Fixed the typo in cstor operator provision test script

---

openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/6-csi-infra-setup/AWES-cstor-operator/cstor-operator

refactor[script]: Updated the version tag for cspc operator provision
